CREATE DATABASE IF NOT EXISTS atto
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE atto;

CREATE TABLE IF NOT EXISTS `user` (
  userId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  mail VARCHAR(150) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (userId),
  UNIQUE KEY uq_user_id (id),
  UNIQUE KEY uq_user_mail (mail)
);

CREATE TABLE IF NOT EXISTS address (
  addressId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId BIGINT UNSIGNED NOT NULL,
  recipientName VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  zipcode VARCHAR(20) NOT NULL,
  address1 VARCHAR(255) NOT NULL,
  address2 VARCHAR(255) DEFAULT NULL,
  isDefault TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (addressId),
  KEY idx_address_userId (userId),
  CONSTRAINT fk_address_user
    FOREIGN KEY (userId) REFERENCES `user` (userId)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS scrap (
  scrapId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId BIGINT UNSIGNED NOT NULL,
  productId BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (scrapId),
  UNIQUE KEY uq_scrap_user_product (userId, productId),
  KEY idx_scrap_userId (userId),
  CONSTRAINT fk_scrap_user
    FOREIGN KEY (userId) REFERENCES `user` (userId)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
  orderId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId BIGINT UNSIGNED NOT NULL,
  paymentId BIGINT UNSIGNED DEFAULT NULL,
  addressId BIGINT UNSIGNED DEFAULT NULL,
  totalAmount INT NOT NULL,
  status ENUM('ORDERED','PREPARING','SHIPPED','DELIVERED','CANCELLED','REFUNDED','EXCHANGED') NOT NULL DEFAULT 'ORDERED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (orderId),
  KEY idx_orders_userId (userId),
  KEY idx_orders_status (status),
  KEY idx_orders_paymentId (paymentId),
  CONSTRAINT fk_orders_user
    FOREIGN KEY (userId) REFERENCES `user` (userId)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_orders_address
    FOREIGN KEY (addressId) REFERENCES address (addressId)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS payment (
  paymentId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId BIGINT UNSIGNED NOT NULL,
  amount INT NOT NULL,
  paymentMethod ENUM('BANK_TRANSFER') NOT NULL DEFAULT 'BANK_TRANSFER',
  status ENUM('PENDING','COMPLETED','REFUNDED') NOT NULL DEFAULT 'PENDING',
  depositorName VARCHAR(100) DEFAULT NULL,
  bankName VARCHAR(100) DEFAULT NULL,
  memo VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (paymentId),
  KEY idx_payment_userId (userId),
  KEY idx_payment_status (status),
  CONSTRAINT fk_payment_user
    FOREIGN KEY (userId) REFERENCES `user` (userId)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
